# Grafana Data Sources Configuration
apiVersion: 1

datasources:
  # Primary Prometheus Data Source
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    isDefault: true
    version: 1
    editable: true
    jsonData:
      httpMethod: POST
      queryTimeout: 300s
      timeInterval: 15s
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: tempo
    
  # Loki for Logs
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    version: 1
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: "trace_id=(\\w+)"
          name: trace_id
          url: "$${__value.raw}"

  # Tempo for Traces (if implemented)
  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    uid: tempo
    url: http://tempo:3200
    version: 1
    editable: true
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: prometheus

  # ElasticSearch for Advanced Log Analysis
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    orgId: 1
    url: http://elasticsearch:9200
    database: "logstash-*"
    version: 1
    editable: true
    jsonData:
      interval: Daily
      timeField: "@timestamp"
      esVersion: "8.8.0"
      maxConcurrentShardRequests: 5
      logMessageField: message
      logLevelField: level

  # Custom Business Metrics Database (if separate)
  - name: Business_Metrics
    type: postgres
    access: proxy
    orgId: 1
    url: postgres:5432
    database: plumbing_ai
    user: grafana_reader
    version: 1
    editable: true
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 14400
    secureJsonData:
      password: "${GRAFANA_DB_PASSWORD}"